### ISSUE TITLE
remove etcd v2 storage package

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/microkit#32]
As soon as we do not rely on etcd v2 we should cleanup the storage packages. 

/cc @JosephSalisbury

**Comment by JosephSalisbury** [comment]
For the record, what are we using etcdv2 for?

**Comment by xh3b4sd** [comment]
Cluster-service on the old leaseweb infrastructure.

**Comment by xh3b4sd** [comment]
No longer a thing.
