### ISSUE TITLE
--service.storage.kind flag should be validated, error in case of bad value

### ISSUE THREAD

**Issue by marians** [giantswarm/microkit#59]
If a microservice only supports `memory` and `etcdv2`, passing something else here should result in the process dying with a useful error message like

```
Unknown storage type `%s` passed via flag --service.storage.kind
```

Currently the process starts without notice or error message, fallling back to memory (it seems). Tested in `cluster-service`.

**Comment by JosephSalisbury** [comment]
I don't follow this part:
> If a microservice only supports `memory` and `etcdv2`

If a service uses microkit, it gets memory, etcd v2 and etcd v3 support out of the box, there's a common storage interface.

Is this issue to do with passing some other string to the flag, and it not being properly validated?

**Comment by marians** [comment]
@JosephSalisbury I started `cluster-service` with `--service.storage.kind=etcd`, and it seemed as if cluster-service silently defaulted to `memory`.

**Comment by xh3b4sd** [comment]
No longer a thing.
