### ISSUE TITLE
juju/errgo unmaintained?

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/microkit#62]
It seems like the error library in this kit has been superseded by [juju/errors](https://github.com/juju/errors).

The advantages I see for errors:
* seems maintained, and is mentioned in [this blogpost](https://npf.io/2017/03/3.5yrs-500k-lines-of-go/) by one of the authors of juju
* clearer readme, outlining e.g. how to use this library in conjunction with type assertion
* clearer implementation. `Mask` now only takes one argument, the error. Cfr [`errgo`](https://github.com/juju/errgo#func--mask): 
* no need to wrap errors all the way up, thanks to the [`ErrorStack`](https://github.com/juju/errors/blob/6f54ff6318409d31ff16261533ce2c8381a4fd5d/functions.go#L262) function.

> By default Mask conceals the cause of the wrapped error, but if pass(Cause(err)) returns true for any of the provided pass functions, the cause of the returned error will be Cause(err).

The cons are, mostly, that the `MaskFunc` is not available anymore, and we use it extensively through [`MaskAny`](https://github.com/giantswarm/microkit/blob/8081cd79373ce7175be0f13ddef5b546521c2a06/error/error.go#L15). AFAIU though, what we do with `MaskAny` is simply what [`errors.Mask`](https://github.com/juju/errors#func-mask) does, i.e. just wrap an error.

**Comment by JosephSalisbury** [comment]
https://github.com/pkg/errors is another possibility, if we do change things about

**Comment by xh3b4sd** [comment]
Is there a concrete problem we have to solve? All this error handling magic is one of these topics that is super expensive to invest in and at out current level, does not seem to bring any real win or more value, as far as I can see.

**Comment by JosephSalisbury** [comment]
No movement. Closing.
